'use strict';
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const { pathToFileURL } = require('node:url');
const htmlPath = path.join(__dirname, 'index.html');
const html = fs.readFileSync(htmlPath, 'utf8');
const code = html.match(/<script id="balance-engine">([\s\S]*?)<\/script>/)[1];
const ui = html.match(/<script id="balance-ui">([\s\S]*?)<\/script>/)[1];
new vm.Script(code); new vm.Script(ui);
const ctx = { module: { exports: {} } };
vm.runInNewContext(code, ctx);
const B = ctx.module.exports;
const combatCode=html.match(/<script id="combat-engine">([\s\S]*?)<\/script>/)[1];
new vm.Script(combatCode);vm.runInNewContext(combatCode,ctx);const C=ctx.module.exports;
let count = 0;
const near = (a,b) => assert.ok(Math.abs(a-b)<1e-7, `${a} != ${b}`);
function test(name, fn) { fn(); count++; console.log('PASS', name); }
function naked() {
 const s = B.defaults(); s.baseDps=1000;
 for(const side of ['v','e']) { s[side].armor='none'; s[side].items.forEach(x=>{x.id='empty';x.prefix='none';}); }
 return s;
}
test('Both naked outputs equal B, including baseline crit normalization',()=>{const r=B.calculate(naked());near(r.vanilla,1000);near(r.elaina,1000);near(r.required,0);});
test('Naked base mana does not count as equipment growth',()=>near(B.calculate(naked()).effective,0));
test('Single Menacing adds 4 percentage points, not a separate multiplier',()=>{const s=naked();s.v.damage=50;s.v.items[0]={id:'utility',prefix:'menacing'};near(B.calculate(s).vanilla,1540);});
test('Single Arcane buys 4% in the explicit budget model',()=>{const s=naked();s.e.items[0]={id:'utility',prefix:'arcane'};const r=B.calculate(s);near(r.maxMana,220);near(r.extra,40);});
test('Damage gain does not compound additively stacked gear',()=>{const s=naked();s.v.armor='hallowed';s.v.items[0]={id:'sorcerer',prefix:'menacing'};near(B.gear(s,'v').damage,38);});
test('Jungle armor aggregation',()=>{const s=naked();s.e.armor='jungle';const g=B.gear(s,'e');near(g.damage,6);near(g.crit,16);near(g.mana,80);});
test('Adamantite armor aggregation',()=>{const s=naked();s.e.armor='adamantite';const g=B.gear(s,'e');near(g.damage,20);near(g.crit,23);near(g.mana,80);});
test('Hallowed armor aggregation',()=>{const s=naked();s.e.armor='hallowed';const g=B.gear(s,'e');near(g.damage,19);near(g.crit,23);near(g.mana,100);});
test('Spectre passive only, no invented proc',()=>{const s=naked();s.e.armor='spectre';near(B.gear(s,'e').damage,25);near(B.gear(s,'e').crit,21);near(s.e.proc,0);});
test('Crit clamps at 100%',()=>{const s=naked();s.e.crit=100;near(B.gear(s,'e').crit,100);near(B.gear(s,'e').multiplier,2/1.04);});
test('Negative crit cannot drop below zero',()=>{const s=naked();s.e.crit=-100;near(B.gear(s,'e').crit,0);});
test('Empty accessories cannot receive prefix bonuses',()=>{const s=naked();s.e.items[0].prefix='arcane';near(B.calculate(s).maxMana,200);});
test('Slots beyond chosen cap are inactive',()=>{const s=naked();s.slots=5;s.e.items[6]={id:'sorcerer',prefix:'arcane'};near(B.calculate(s).elaina,1000);});
test('Manual fixed skill budget has no automatic maximum-mana benefit',()=>{const s=naked();s.budgetSource='manual';near(B.marginal(s).mana,0);});
test('Reserve is subtracted before conversion',()=>{const s=naked();s.extraMana=100;s.reserve=20;s.use=50;near(B.calculate(s).effective,40);});
test('Reserve cannot create a negative output',()=>{const s=naked();s.reserve=10000;near(B.calculate(s).effective,0);});
test('Zero conversion disables bonus output',()=>{const s=B.defaults();s.use=0;near(B.calculate(s).extra,0);});
test('Total pool mode explicitly includes baseline mana',()=>{const s=naked();s.budgetSource='total';near(B.calculate(s).effective,200);near(B.calculate(s).extra,400);});
test('Common stats on skills can be disabled',()=>{const s=naked();s.e.damage=50;s.extraMana=100;s.skillStats=false;near(B.calculate(s).extra,200);s.skillStats=true;near(B.calculate(s).extra,300);});
test('Preset skill list sums cost times quality times realization',()=>{const s=naked();s.mode='skills';near(B.calculate(s).effective,157);near(B.calculate(s).extra,314);});
test('Skill list ignores automatic mana budget parameters',()=>{const s=naked();s.mode='skills';s.use=0;s.quality=0;s.reserve=10000;near(B.calculate(s).effective,157);});
test('Skill realization affects only its own contribution',()=>{const s=naked();s.mode='skills';s.skills.forEach(x=>x.enabled=false);s.skills[0].enabled=true;s.skills[0].realization=50;near(B.calculate(s).effective,50);});
test('No mana marginal gain is invented for unchanged skill list',()=>{const s=naked();s.mode='skills';near(B.marginal(s).mana,0);});
test('No cooldown or mana-reduction axis is present',()=>{const s=B.defaults();assert.equal(s.cooldown,undefined);assert.equal(s.manaReduction,undefined);});
test('Required equivalent budget solves equal DPS',()=>{const s=naked();s.v.damage=40;const r=B.calculate(s);near(r.required,200);s.budgetSource='manual';s.manualBudget=r.required;near(B.calculate(s).elaina,r.vanilla);});
test('Zero rate and positive gap reports impossible instead of NaN',()=>{const s=naked();s.v.damage=40;s.rate=0;assert.equal(B.calculate(s).required,Infinity);});
test('Zero rate and no gap requires no budget',()=>{const s=naked();s.rate=0;near(B.calculate(s).required,0);});
test('Custom proc damage enters output once',()=>{const s=naked();s.v.proc=300;s.e.proc=200;near(B.calculate(s).vanilla,1300);near(B.calculate(s).elaina,1200);near(B.calculate(s).required,50);});
test('Displayed recovery uses local mod parameters, not DPS bonus',()=>{const s=naked();near(B.calculate(s).recovery,9);near(B.calculate(s).elaina,1000);});
test('Changing B scales outputs without changing required budget',()=>{const a=B.defaults(),b=B.clone(a);b.baseDps=a.baseDps*3;const x=B.calculate(a),y=B.calculate(b);near(y.elaina,x.elaina*3);near(y.required,x.required);});
test('Growth experiment uses zero through slot-count prefixes',()=>{const s=B.defaults();const rows=B.growth(s);assert.equal(rows.length,s.slots+1);near(rows[0].e.defense,24);near(rows[6].e.defense,0);near(rows[6].e.mana-rows[0].e.mana,120);});
test('Growth does not mutate configuration',()=>{const s=B.defaults(),before=JSON.stringify(s);B.growth(s);assert.equal(JSON.stringify(s),before);});
test('Marginals do not mutate configuration',()=>{const s=B.defaults(),before=JSON.stringify(s);B.marginal(s);assert.equal(JSON.stringify(s),before);});
test('All default presets produce finite results',()=>{for(const key of Object.keys(B.presets)){const r=B.calculate(B.defaults(key));assert.ok(Number.isFinite(r.vanilla)&&Number.isFinite(r.elaina)&&Number.isFinite(r.required));}});
test('Static IDs are unique',()=>{const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(x=>x[1]);assert.equal(ids.length,new Set(ids).size);});
test('Standalone has no external script/style/network dependency',()=>{assert.ok(!/<script[^>]+src=|<link[^>]+href=|\bfetch\(/.test(html));});
test('Injury defaults to zero and preserves original results',()=>{const s=B.defaults(),r=B.calculate(s);near(s.hurtMana,0);near(r.lostDps,0);near(r.unhurtDps,r.elaina);});
test('Injury subtracts spent mana, not effective mana',()=>{const s=naked();s.extraMana=100;s.quality=.5;s.hurtMana=20;const r=B.calculate(s);near(r.rawBudget,80);near(r.effective,40);near(r.lostDps,20);});
test('Injury never reduces mana maximum, regeneration or auto DPS',()=>{const s=B.defaults(),a=B.calculate(s);s.hurtMana=100;const b=B.calculate(s);near(a.maxMana,b.maxMana);near(a.recovery,b.recovery);near(a.auto,b.auto);near(a.vanilla,b.vanilla);});
test('Injury over budget zeroes skills but cannot subtract ordinary attacks',()=>{const s=B.defaults();s.hurtMana=10000;const r=B.calculate(s);near(r.effective,0);near(r.elaina,r.auto+s.e.proc);near(r.rawBudget,0);});
test('Reserve and conversion happen before net injury deduction',()=>{const s=naked();s.extraMana=200;s.reserve=20;s.use=50;s.hurtMana=30;const r=B.calculate(s);near(r.plannedBudget,90);near(r.rawBudget,60);});
test('Manual budgets also account for injury',()=>{const s=naked();s.budgetSource='manual';s.manualBudget=100;s.hurtMana=20;near(B.calculate(s).effective,80);});
test('Skill list distributes injury proportionally',()=>{const s=naked();s.mode='skills';s.hurtMana=80;const r=B.calculate(s);near(r.plannedBudget,160);near(r.retained,.5);near(r.effective,78.5);near(r.lostDps,157);});
test('Partially realized skills weight both mana and damage',()=>{const s=naked();s.mode='skills';s.skills.forEach(x=>x.enabled=false);s.skills[0].enabled=true;s.skills[0].realization=50;s.hurtMana=20;const r=B.calculate(s);near(r.plannedBudget,50);near(r.effective,30);});
test('No skills or budget produces finite zero injury loss',()=>{const s=naked();s.mode='skills';s.skills.forEach(x=>x.enabled=false);s.hurtMana=200;const r=B.calculate(s);near(r.retained,0);near(r.effective,0);near(r.lostDps,0);});
test('Missing injury property remains compatible in the engine',()=>{const s=B.defaults();delete s.hurtMana;near(B.calculate(s).lostDps,0);});

function combatBase(){const s=naked();s.skills.forEach(x=>x.enabled=false);Object.assign(s.combat,{duration:10,potions:0,regenMode:'manual',regen:0,autoCost:0,autoInterval:.5});return s;}
function onlySkill(s){const x=s.skills[0];Object.assign(x,{enabled:true,cost:100,k:1,cd:10,cast:1,delay:0,duration:0,maxCharges:1,initialCharges:1,first:0,priority:1,hit:100});return x;}
function ledger(r){near(r.initialMana+r.regenEffective+r.potionEffective-r.autoMana-r.skillMana-r.hurtPaid,r.endMana);assert.ok(r.endMana>=-1e-7&&r.endMana<=r.maxMana+1e-7);}
test('Combat naked free auto reproduces base DPS',()=>{const r=C.run(combatBase());near(r.dps,1000);near(r.autoCount,20);ledger(r);});
test('Combat fixed mana limits attack count',()=>{const s=combatBase();s.combat.autoCost=50;const r=C.run(s);near(r.autoCount,4);near(r.endMana,0);near(r.firstShortage,2);ledger(r);});
test('Combat zero opening mana means no free paid attacks',()=>{const s=combatBase();s.combat.startPercent=0;s.combat.autoCost=3;near(C.run(s).autoDamage,0);});
test('Combat five potions add exactly 2.5 pools when fully spent',()=>{const s=combatBase();Object.assign(s.combat,{duration:20,potions:5,autoCost:50});const r=C.run(s);near(r.usedPotions,5);near(r.autoCount,14);near(r.potionEffective,500);near(r.fifthPotionTime,6);near(r.lastPotionTime,6);ledger(r);});
test('Atomic payment does not waste insufficient potion charges',()=>{const s=combatBase();Object.assign(s.combat,{startPercent:0,potions:1,autoCost:200});const r=C.run(s);near(r.usedPotions,0);near(r.potionsLeft,1);near(r.autoCount,0);});
test('Atomic payment can use several bottles at once',()=>{const s=combatBase();Object.assign(s.combat,{duration:1,startPercent:0,potions:5,autoCost:200});const r=C.run(s);near(r.autoCount,2);near(r.usedPotions,4);ledger(r);});
test('Cost above maximum is never cast in resource simulation',()=>{const s=combatBase();onlySkill(s).cost=201;const r=C.run(s);near(r.skills[0].count,0);assert.equal(r.invalid.length,1);});
test('Unrestricted reference still shows impossible skill potential',()=>{const s=combatBase();onlySkill(s).cost=201;near(C.run(s,true).skills[0].count,1);});
test('Cast occupancy is compensated once, not added over uninterrupted autos',()=>{const s=combatBase();onlySkill(s);const r=C.run(s);near(r.autoDamage,9000);near(r.skillDamage,3000);near(r.dps,1200);});
test('Cooldown bounds cast count and excludes an action at the end',()=>{const s=combatBase();s.combat.duration=30;onlySkill(s);near(C.run(s,true).skills[0].count,3);});
test('Initial empty charges recover after a full cooldown',()=>{const s=combatBase();s.combat.duration=20;onlySkill(s).initialCharges=0;const r=C.run(s,true);near(r.skills[0].count,1);near(r.events.find(e=>e.type==='cast').time,10);});
test('Five stored charges refill serially, not five per cooldown',()=>{const s=combatBase();s.combat.duration=25;Object.assign(onlySkill(s),{cast:.1,maxCharges:5,initialCharges:5});near(C.run(s,true).skills[0].count,7);});
test('First release time is respected',()=>{const s=combatBase();s.combat.duration=30;onlySkill(s).first=15;const r=C.run(s,true);near(r.skills[0].count,2);near(r.events.find(e=>e.type==='cast').time,15);});
test('Damage after battle end is not credited',()=>{const s=combatBase();Object.assign(onlySkill(s),{cast:1,delay:20});const r=C.run(s);near(r.skills[0].count,1);near(r.skillDamage,0);});
test('DoT is clipped at battle end',()=>{const s=combatBase();Object.assign(onlySkill(s),{cast:1,delay:0,duration:20});near(C.run(s).skillDamage,3000*9/20);});
test('Hit rate affects damage but not cost',()=>{const s=combatBase();onlySkill(s).hit=50;const r=C.run(s);near(r.skillDamage,1500);near(r.skillMana,100);});
test('Legacy realization and injury do not double-discount combat',()=>{const s=combatBase();onlySkill(s);const a=C.run(s);s.skills[0].realization=0;s.hurtMana=10000;s.use=0;near(C.run(s).dps,a.dps);});
test('Uniform injuries integrate their full requested total',()=>{const s=combatBase();s.combat.hurtTotal=100;const r=C.run(s);near(r.hurtRequested,100);near(r.hurtPaid,100);near(r.endMana,100);ledger(r);});
test('Insufficient defensive mana never goes negative',()=>{const s=combatBase();s.combat.hurtTotal=500;const r=C.run(s);near(r.hurtPaid,200);near(r.uncoveredHurt,300);near(r.endMana,0);});
test('Periodic injuries occur at intervals, not at time zero or T',()=>{const s=combatBase();Object.assign(s.combat,{duration:30,hurtMode:'periodic',hurtInterval:10,hurtPerHit:40});near(C.run(s).hurtRequested,80);});
test('Explicit injury event at zero precedes casting',()=>{const s=combatBase();Object.assign(s.combat,{hurtMode:'events',hurtEvents:'0:200',autoCost:3});const r=C.run(s);near(r.hurtPaid,200);near(r.autoCount,0);});
test('Injury in the final subframe is not lost',()=>{const s=combatBase();s.combat.hurtMode='events';s.combat.hurtEvents='9.999:40';near(C.run(s).hurtRequested,40);});
test('Malformed and out-of-battle injury lines are reported',()=>{const s=combatBase();s.combat.hurtMode='events';s.combat.hurtEvents='bad\n12:40\n5:20';const r=C.run(s);assert.equal(r.injuryErrors.length,2);near(r.hurtRequested,20);});
test('Full mana regeneration is counted as waste',()=>{const s=combatBase();s.combat.regen=10;const r=C.run(s);near(r.regenWaste,100);near(r.regenEffective,0);ledger(r);});
test('Active reserve prevents skill spending but permits ordinary attack',()=>{const s=combatBase();onlySkill(s);s.combat.reserve=150;const r=C.run(s);near(r.skillMana,0);near(r.dps,1000);});
test('Save strategy can stop autos to accumulate for a ready skill',()=>{const s=combatBase();onlySkill(s);Object.assign(s.combat,{startPercent:0,regen:10,autoCost:3,duration:20,policy:'save'});const save=C.run(s);s.combat.policy='flow';const flow=C.run(s);assert.ok(save.skills[0].count>flow.skills[0].count);ledger(save);ledger(flow);});
test('Skill priority chooses the first action deterministically',()=>{const s=combatBase();onlySkill(s);s.skills[2].enabled=true;s.skills[2].priority=1;s.skills[0].priority=2;assert.match(C.run(s,true).events.find(e=>e.type==='cast').text,/炎爆/);});
test('Adding an unpayable skill does not invent extra damage',()=>{const s=combatBase();s.combat.startPercent=0;s.combat.autoCost=0;const a=C.run(s);onlySkill(s);near(C.run(s).dps,a.dps);});
test('Regen and potion settings do not alter unlimited reference output',()=>{const s=B.defaults();const a=C.run(s,true);s.combat.potions=0;s.combat.regenMode='manual';s.combat.regen=0;near(C.run(s,true).dps,a.dps);});
test('Total damage equals its contributors',()=>{const s=B.defaults();s.e.proc=123;const r=C.run(s);near(r.totalDamage,r.autoDamage+r.skillDamage+r.procDamage);near(r.dps*r.T,r.totalDamage);ledger(r);});
test('Simulation does not mutate input',()=>{const s=B.defaults(),before=JSON.stringify(s);C.compare(s);assert.equal(JSON.stringify(s),before);});
test('Deterministic resource conservation across varied configurations',()=>{for(let n=0;n<16;n++){const s=B.defaults();s.combat.duration=30+n*3;s.combat.potions=n%6;s.combat.hurtTotal=n*35;s.extraMana=n*20;s.combat.startPercent=20+n*5;s.combat.policy=n%2?'flow':'save';s.skills[n%7].enabled=true;const r=C.run(s);ledger(r);assert.ok(r.usedPotions<=s.combat.potions);assert.ok(r.samples.every(x=>x.mana>=-1e-7&&x.mana<=r.maxMana+1e-7));}});

test('Nebula unbuffed armor has 26 damage,16 crit,60 mana and 46 defense',()=>{const s=naked();s.e.armor='nebula';s.e.nebula={damage:0,mana:0,life:0};const g=B.gear(s,'e');near(g.damage,26);near(g.crit,20);near(g.mana,60);near(g.armorDefense,46);near(g.manaReduction,15);near(g.moveSpeed,10);});
test('Full Nebula buffs add 45 damage,30 mana/s and 9 life/s',()=>{const s=naked();s.e.armor='nebula';const g=B.gear(s,'e');near(g.damage,71);near(g.nebulaDamage,45);near(g.nebulaManaRegen,30);near(g.nebulaLifeRegen,9);near(g.crit,20);});
test('Nebula damage is additive to equipment, not a separate 45% multiplier',()=>{const s=naked();s.v.armor='nebula';s.v.damage=20;const g=B.gear(s,'v');near(g.damage,91);near(g.multiplier,1.91*1.2/1.04);});
test('Independent Nebula stack counts apply per buff and per player',()=>{const s=naked();s.v.armor='nebula';s.e.armor='nebula';s.e.nebula={damage:1,mana:2,life:0};const e=B.gear(s,'e'),v=B.gear(s,'v');near(e.damage,41);near(e.nebulaManaRegen,20);near(e.nebulaLifeRegen,0);near(v.damage,71);});
test('Removing Nebula armor disables its stored buffs and mana bridge',()=>{const s=B.defaults('nebula');s.nebulaManaBridge=true;s.e.armor='none';const r=C.run(s);near(B.gear(s,'e').nebulaDamage,0);near(r.nebulaRegen,0);near(r.regen,5+r.maxMana*.02);});
test('Current-code preset does not silently restore special mana',()=>{const s=B.defaults('nebula');assert.equal(s.nebulaManaBridge,false);const r=C.run(s);near(r.nebulaRegen,0);near(r.regen,5+r.maxMana*.02);});
test('Optional Nebula bridge adds exactly 30/s to special regeneration',()=>{const s=B.defaults('nebula'),a=C.run(s);s.nebulaManaBridge=true;const r=C.run(s);near(r.regen,a.regen+30);near(r.nebulaRegen,30);near(B.calculate(s).recovery,r.regen);near(r.maxMana,a.maxMana);ledger(r);});
test('Manual base regen plus Nebula is added exactly once',()=>{const s=B.defaults('nebula');s.nebulaManaBridge=true;s.combat.regenMode='manual';s.combat.regen=7;const r=C.run(s);near(r.baseRegen,7);near(r.regen,37);});
test('Nebula life buff does not create damage, mana or absorb injuries',()=>{const s=B.defaults('nebula');s.combat.hurtTotal=200;const a=C.run(s);s.e.nebula.life=0;const r=C.run(s);near(r.totalDamage,a.totalDamage);near(r.hurtPaid,a.hurtPaid);near(r.endMana,a.endMana);});
test('Nebula 15% vanilla reduction never discounts special skill or auto cost',()=>{const s=combatBase();s.e.armor='nebula';onlySkill(s);s.combat.autoCost=2;const r=C.run(s);near(r.skillMana,r.skills[0].count*100);near(r.autoMana,r.autoCount*2);});
test('Graduate preset uses KL 3500 base and full buffs on both sides',()=>{const s=B.defaults('nebula');near(s.baseDps,3500);assert.equal(s.v.armor,'nebula');assert.equal(s.e.armor,'nebula');near(B.gear(s,'v').nebulaDamage,45);near(B.gear(s,'e').nebulaLifeRegen,9);});
test('Zero mana stacks cannot grant bridge recovery',()=>{const s=B.defaults('nebula');s.nebulaManaBridge=true;s.e.nebula.mana=0;near(C.run(s).nebulaRegen,0);});
console.log(`\n${count} model/static tests passed.`);
console.log('Default result:', JSON.stringify(B.calculate(B.defaults()),null,2));

async function browserTests(){
 // Isolated disposable browser for this local HTML; no user browser profile or session is used.
 const runtime = process.env.CODEX_NODE_MODULES || 'C:/Users/korateleng/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules';
 const {chromium}=require(path.join(runtime,'playwright'));
 const browser=await chromium.launch({headless:true, channel:process.env.BALANCE_BROWSER_CHANNEL || 'chrome'});
 try {
  fs.mkdirSync(path.join(__dirname,'test-output'),{recursive:true});
  const page=await browser.newPage({viewport:{width:1440,height:1100},deviceScaleFactor:1});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(pathToFileURL(htmlPath).href);
  await page.getByRole('button',{name:'恢复默认'}).click();

  // Bulk prefixes change only the requested side's active, occupied slots.
  const values=async(side,prop)=>page.locator('#'+side+'Slots select[data-prop="'+prop+'"]').evaluateAll(els=>els.map(el=>el.value));
  const initialVItems=await values('v','id'),initialEItems=await values('e','id');
  const initialEPrefixes=await values('e','prefix');
  const beforePrefixDps=await page.locator('#simVanilla').innerText();
  await page.getByRole('button',{name:'原版法师全险恶',exact:true}).click();
  assert.ok((await values('v','prefix')).every(v=>v==='menacing'));
  assert.deepEqual(await values('e','prefix'),initialEPrefixes);
  assert.notEqual(await page.locator('#simVanilla').innerText(),beforePrefixDps);
  await page.getByRole('button',{name:'原版法师全奥秘',exact:true}).click();
  assert.ok((await values('v','prefix')).every(v=>v==='arcane'));
  await page.getByRole('button',{name:'伊蕾娜全险恶',exact:true}).click();
  assert.ok((await values('e','prefix')).every(v=>v==='menacing'));
  const beforeArcane=await page.locator('#simCapacity').innerText();
  await page.getByRole('button',{name:'伊蕾娜全奥秘',exact:true}).click();
  assert.ok((await values('e','prefix')).every(v=>v==='arcane'));
  assert.notEqual(await page.locator('#simCapacity').innerText(),beforeArcane);
  assert.deepEqual(await values('v','id'),initialVItems);
  assert.deepEqual(await values('e','id'),initialEItems);
  await page.reload();
  assert.ok((await values('v','prefix')).every(v=>v==='arcane'));
  assert.ok((await values('e','prefix')).every(v=>v==='arcane'));
  await page.locator('#slots').selectOption('7');
  await page.locator('#eSlots select[data-prop="prefix"]').nth(6).selectOption('lucky');
  await page.locator('#slots').selectOption('5');
  await page.locator('#eSlots select[data-prop="id"]').first().selectOption('empty');
  await page.locator('#eSlots select[data-prop="prefix"]').first().selectOption('warding');
  await page.getByRole('button',{name:'伊蕾娜全险恶',exact:true}).click();
  assert.deepEqual(await values('e','prefix'),['warding','menacing','menacing','menacing','menacing']);
  assert.match(await page.locator('#ePrefixStatus').innerText(),/4 个/);
  await page.locator('#slots').selectOption('7');
  assert.equal((await values('e','prefix'))[6],'lucky');
  await page.getByRole('button',{name:'恢复默认'}).click();

  // Graduate preset, three independent buff stacks and explicit special-mana adaptation.
  await page.locator('#preset').selectOption('nebula');
  assert.equal(await page.locator('#baseDps').inputValue(),'3500');
  assert.ok(await page.locator('#vNebula').isVisible());
  assert.ok(await page.locator('#eNebula').isVisible());
  assert.equal(await page.locator('#vNebulaDamage').inputValue(),'3');
  assert.equal(await page.locator('#eNebulaMana').inputValue(),'3');
  assert.equal(await page.locator('#nebulaManaBridge').isChecked(),false);
  assert.match(await page.locator('#eNebulaInfo').innerText(),/\+45% 加算伤害、\+30 原版魔力\/秒、\+9 生命\/秒/);
  const fullNebulaDps=await page.locator('#simVanilla').innerText();
  await page.locator('#vNebulaDamage').selectOption('0');
  assert.notEqual(await page.locator('#simVanilla').innerText(),fullNebulaDps);
  assert.equal(await page.locator('#eNebulaDamage').inputValue(),'3');
  await page.getByRole('button',{name:'原版法师星云强化全满',exact:true}).click();
  assert.equal(await page.locator('#simVanilla').innerText(),fullNebulaDps);
  const beforeBridge=await page.locator('#simCapacity').innerText();
  await page.locator('#nebulaManaBridge').check();
  assert.notEqual(await page.locator('#simCapacity').innerText(),beforeBridge);
  assert.match(await page.locator('#simCapacity').innerText(),/星云 30/);
  await page.locator('#eNebulaMana').selectOption('1');
  assert.match(await page.locator('#simCapacity').innerText(),/星云 10/);
  await page.reload();
  assert.equal(await page.locator('#nebulaManaBridge').isChecked(),true);
  assert.equal(await page.locator('#eNebulaMana').inputValue(),'1');
  await page.getByRole('button',{name:'伊蕾娜星云强化全满',exact:true}).click();
  await page.locator('#eNebula').screenshot({path:path.join(__dirname,'test-output','nebula-buffs.png')});
  await page.setViewportSize({width:390,height:844});
  await page.locator('#eNebula').screenshot({path:path.join(__dirname,'test-output','nebula-mobile.png')});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false);
  await page.setViewportSize({width:1440,height:1100});
  await page.locator('#eArmor').selectOption('hallowed');
  assert.equal(await page.locator('#eNebula').isVisible(),false);
  assert.doesNotMatch(await page.locator('#simCapacity').innerText(),/星云/);
  await page.locator('#vNebulaLife').selectOption('1');
  await page.getByRole('button',{name:'复制左侧装备 · 前缀转奥秘'}).click();
  assert.equal(await page.locator('#eNebulaLife').inputValue(),'1');
  await page.getByRole('button',{name:'恢复默认'}).click();
  // Exercise the new resource-limited simulation before the legacy-budget regression suite.
  const initialSim=await page.locator('#simActual').innerText();
  const initialIdeal=await page.locator('#simIdeal').innerText();
  await page.locator('#battlePotions').fill('0');
  assert.notEqual(await page.locator('#simActual').innerText(),initialSim);
  assert.equal(await page.locator('#simIdeal').innerText(),initialIdeal);
  assert.equal(await page.locator('#simPotionEnd').innerText(),'未携带');
  await page.getByRole('button',{name:'长战 180 秒',exact:true}).click();
  assert.equal(await page.locator('#battleDuration').inputValue(),'180');
  await page.locator('#battleRegenMode').selectOption('manual');
  await page.locator('#battleRegen').fill('0');
  await page.locator('#battleStart').fill('0');
  assert.equal(await page.locator('#simActual').innerText(),'0');
  await page.locator('#battlePolicy').selectOption('save');
  await page.getByRole('button',{name:'恢复默认'}).click();
  await page.getByText('受伤损蓝：均匀损失、周期受击或指定时间',{exact:true}).click();
  await page.locator('#battleHurtTotal').fill('500');
  assert.notEqual(await page.locator('#simActual').innerText(),initialSim);
  await page.locator('#battleHurtMode').selectOption('events');
  await page.locator('#battleHurtEvents').fill('0:380\nbad\n150:20');
  assert.match(await page.locator('#simWarnings').innerText(),/格式错误/);
  await page.locator('#battleHurtMode').selectOption('periodic');
  assert.ok(await page.locator('#battleHurtInterval').isVisible());
  await page.locator('#battleHurtPerHit').fill('50');
  await page.locator('#battleHurtInterval').fill('20');
  await page.getByRole('checkbox',{name:'模拟启用冰凌锁',exact:true}).check();
  await page.getByRole('spinbutton',{name:'模拟冰凌锁蓝耗',exact:true}).fill('500');
  assert.match(await page.locator('#simWarnings').innerText(),/无法支付/);
  await page.getByRole('spinbutton',{name:'模拟水球魔法CD',exact:true}).fill('30');
  await page.getByRole('spinbutton',{name:'模拟水球魔法命中',exact:true}).fill('50');
  await page.reload();
  assert.equal(await page.getByRole('spinbutton',{name:'模拟水球魔法CD',exact:true}).inputValue(),'30');
  assert.equal(await page.locator('#battleHurtMode').inputValue(),'periodic');
  await page.getByRole('button',{name:'恢复默认'}).click();
  await page.locator('#legacyResults > summary').click();
  await page.locator('#vDps').waitFor();
  const beforeHurt=await page.locator('#eDps').innerText();
  await page.locator('#hurtMana').fill('60');
  assert.notEqual(await page.locator('#eDps').innerText(),beforeHurt);
  assert.equal(await page.locator('#mana').innerText(),'380');
  assert.equal(await page.locator('#effective').innerText(),'120');
  await page.reload();
  await page.locator('#legacyResults').evaluate(el=>el.open=true);
  assert.equal(await page.locator('#hurtMana').inputValue(),'60');
  await page.locator('#hurtMana').fill('10000');
  assert.equal(await page.locator('#effective').innerText(),'0');
  assert.match(await page.locator('#hurtExplain').innerText(),/超出部分不继续扣普攻/);
  await page.locator('#hurtMana').fill('0');
  assert.equal(await page.locator('#eDps').innerText(),beforeHurt);
  const before=await page.locator('#eDps').innerText();
  await page.locator('#extraMana').fill('200');
  assert.notEqual(await page.locator('#eDps').innerText(),before);
  await page.locator('#use').fill('0');
  assert.match(await page.locator('#eDetail').innerText(),/技能 0/);
  await page.locator('#mode').selectOption('skills');
  assert.ok(await page.locator('#skillControls').isVisible());
  assert.ok(!(await page.locator('#budgetControls').isVisible()));
  assert.equal(await page.locator('#effective').innerText(),'157');
  await page.locator('#hurtMana').fill('80');
  assert.equal(await page.locator('#effective').innerText(),'78.5');
  assert.equal(await page.locator('#skillValue0').innerText(),'50');
  await page.locator('#hurtMana').fill('0');
  await page.getByRole('checkbox',{name:'启用水球魔法',exact:true}).uncheck();
  assert.equal(await page.locator('#effective').innerText(),'57');
  await page.locator('#slots').selectOption('7');
  assert.equal(await page.locator('#eSlots .slot').count(),7);
  await page.getByRole('button',{name:'复制左侧装备 · 前缀转奥秘'}).click();
  assert.equal(await page.locator('#eSlots select[data-prop="prefix"]').first().inputValue(),'arcane');
  await page.reload();
  await page.locator('#legacyResults').evaluate(el=>el.open=true);
  assert.equal(await page.locator('#slots').inputValue(),'7');
  assert.equal(await page.locator('#mode').inputValue(),'skills');
  await page.locator('#preset').selectOption('spectre');
  assert.equal(await page.locator('#baseDps').inputValue(),'1800');
  assert.match(await page.locator('#vSummary').innerText(),/追击未自动计入/);
  await page.locator('#vSlots select[data-prop="id"]').nth(1).selectOption('sorcerer');
  assert.match(await page.locator('#vSummary').innerText(),/重复装备/);
  await page.getByRole('button',{name:'恢复默认'}).click();
  const out=path.join(__dirname,'test-output');fs.mkdirSync(out,{recursive:true});
  await page.locator('#hurtMana').fill('60');
  await page.getByText('受伤损蓝：均匀损失、周期受击或指定时间',{exact:true}).evaluate(el=>el.parentElement.open=true);
  await page.locator('#battleHurtMode').selectOption('uniform');
  await page.locator('#battleHurtTotal').fill('240');
  await page.screenshot({path:path.join(out,'desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:path.join(out,'mobile.png'),fullPage:true});
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);
  assert.equal(overflow,false,'Mobile document must not overflow horizontally');
  await page.locator('#mode').selectOption('skills');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false);
  await page.setViewportSize({width:1440,height:1100});
  await page.getByRole('button',{name:'恢复默认'}).click();
  const [download]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'导出当前试算'}).click()]);
  assert.equal(download.suggestedFilename(),'elaina-mage-balance.json');
  const downloadPath=await download.path();const exported=JSON.parse(fs.readFileSync(downloadPath,'utf8'));
  assert.equal(exported.schema,'elaina-mage-balance-v1');near(exported.combat.actual.dps,C.run(B.defaults()).dps);near(exported.result.elaina,B.calculate(B.defaults()).elaina);

  // Import/export round-trip, legacy migration and transactional rejection.
  const importPayload=async(value,name='configuration.json')=>{
   const [chooser]=await Promise.all([page.waitForEvent('filechooser'),page.getByRole('button',{name:'导入配置',exact:true}).click()]);
   await chooser.setFiles({name,mimeType:'application/json',buffer:Buffer.from(typeof value==='string'?value:JSON.stringify(value))});
   await page.waitForFunction(()=>!document.getElementById('import').disabled);
  };
  await page.locator('#extraMana').fill('900');
  await importPayload(exported);
  assert.equal(await page.locator('#extraMana').inputValue(),'0');
  assert.match(await page.locator('#status').innerText(),/已导入/);
  near(Number((await page.locator('#simActual').innerText()).replaceAll(',','')),Math.round(exported.combat.actual.dps*10)/10);
  const customized=B.defaults('nebula');customized.extraMana=240;customized.nebulaManaBridge=true;customized.combat.duration=180;customized.e.nebula.life=1;customized.skills[0].cost=130;
  await importPayload({schema:'elaina-mage-balance-v1',configuration:customized,result:{elaina:-123},combat:{actual:{dps:-123}}});
  assert.equal(await page.locator('#preset').inputValue(),'nebula');
  assert.equal(await page.locator('#battleDuration').inputValue(),'180');
  assert.equal(await page.locator('#eNebulaLife').inputValue(),'1');
  assert.equal(await page.getByRole('spinbutton',{name:'模拟水球魔法蓝耗',exact:true}).inputValue(),'130');
  assert.equal(await page.locator('#nebulaManaBridge').isChecked(),true);
  await page.reload();
  assert.equal(await page.locator('#extraMana').inputValue(),'240');
  const retained=await page.locator('#simActual').innerText();
  for(const bad of ['{bad json',null,[],{schema:'future',configuration:customized},{version:1}, {...customized,baseDps:1000001},{...customized,preset:'toString'},{...customized,skills:[null]}]){
   await importPayload(bad===null?'null':bad);
   assert.match(await page.locator('#status').innerText(),/导入失败，当前配置未改变/);
   assert.equal(await page.locator('#extraMana').inputValue(),'240');
   assert.equal(await page.locator('#simActual').innerText(),retained);
  }
  const invalidArmor=B.clone(customized);invalidArmor.e.armor='constructor';await importPayload(invalidArmor);
  assert.match(await page.locator('#status').innerText(),/导入失败/);
  const legacyImport=B.clone(customized);delete legacyImport.nebulaManaBridge;delete legacyImport.combat;delete legacyImport.v.nebula;delete legacyImport.e.nebula;delete legacyImport.hurtMana;
  for(const row of legacyImport.skills)for(const k of ['cd','cast','delay','duration','maxCharges','initialCharges','first','priority','hit'])delete row[k];
  await importPayload('﻿'+JSON.stringify(legacyImport));
  assert.match(await page.locator('#status').innerText(),/已导入/);
  assert.equal(await page.locator('#extraMana').inputValue(),'240');
  assert.equal(await page.locator('#battleDuration').inputValue(),'120');
  assert.equal(await page.locator('#nebulaManaBridge').isChecked(),false);
  // Re-selecting the same file remains possible; unknown payload keys are not stored.
  await importPayload({...customized,unexpected:'discard me'});
  await importPayload({...customized,unexpected:'discard me'});
  assert.equal(await page.evaluate(()=>Object.hasOwn(JSON.parse(localStorage.getItem('elaina-mage-balance-v1')),'unexpected')),false);
  await page.getByRole('button',{name:'恢复默认'}).click();
  await page.locator('#extraMana').fill('120');
  await page.evaluate(()=>{const key='elaina-mage-balance-v1';const legacy=JSON.parse(localStorage.getItem(key));delete legacy.hurtMana;delete legacy.combat;delete legacy.nebulaManaBridge;delete legacy.v.nebula;delete legacy.e.nebula;for(const row of legacy.skills)for(const k of ['cd','cast','delay','duration','maxCharges','initialCharges','first','priority','hit'])delete row[k];localStorage.setItem(key,JSON.stringify(legacy));});
  await page.reload();
  await page.locator('#legacyResults').evaluate(el=>el.open=true);
  assert.equal(await page.locator('#extraMana').inputValue(),'120');
  assert.equal(await page.locator('#hurtMana').inputValue(),'0');
  assert.equal(await page.locator('#battlePotions').inputValue(),'5');
  assert.equal(await page.getByRole('spinbutton',{name:'模拟水球魔法CD',exact:true}).inputValue(),'20');
  assert.deepEqual(errors,[]);
  console.log('Browser smoke passed: budget/skill updates, presets, slot count, copy, persistence, duplicate warning, export, desktop/mobile layout; zero JS errors.');
 } finally {await browser.close();}
}
if(process.argv.includes('--browser'))browserTests().catch(e=>{console.error(e);process.exitCode=1;});

