'use strict';
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const { pathToFileURL } = require('node:url');
const htmlPath = path.join(__dirname, 'index.html');
const html = fs.readFileSync(htmlPath, 'utf8');
const code = html.match(/<script id="balance-engine">([\s\S]*?)<\/script>/)[1];
const ui = html.match(/<script id="balance-ui">([\s\S]*?)<\/script>/)[1];
new vm.Script(code); new vm.Script(ui);
const ctx = { module: { exports: {} } };
vm.runInNewContext(code, ctx);
const B = ctx.module.exports;
const combatCode=html.match(/<script id="combat-engine">([\s\S]*?)<\/script>/)[1];
new vm.Script(combatCode);vm.runInNewContext(combatCode,ctx);const C=ctx.module.exports;
let count = 0;
const near = (a,b) => assert.ok(Math.abs(a-b)<1e-7, `${a} != ${b}`);
function test(name, fn) { fn(); count++; console.log('PASS', name); }
function naked() {
 const s = B.defaults(); s.baseDps=1000; s.basicAttacks[0].ratio=1; // isolate legacy balance arithmetic from the new 0.8 default
 for(const side of ['v','e']) { s[side].armor='none'; s[side].items.forEach(x=>{x.id='empty';x.prefix='none';}); }
 return s;
}
test('MagicMissileSkill defaults to 80% of the reference DPS and is not an active skill',()=>{const s=B.defaults();near(s.basicAttacks[0].ratio,.8);near(B.calculate(s).auto/s.baseDps/B.gear(s,'e').multiplier,.8);assert.equal(s.skills.some(x=>x.id==='MagicMissileSkill'),false);});
test('Both naked outputs equal B, including baseline crit normalization',()=>{const r=B.calculate(naked());near(r.vanilla,1000);near(r.elaina,1000);near(r.required,0);});
test('Naked base mana does not count as equipment growth',()=>near(B.calculate(naked()).effective,0));
test('Single Menacing adds 4 percentage points, not a separate multiplier',()=>{const s=naked();s.v.damage=50;s.v.items[0]={id:'utility',prefix:'menacing'};near(B.calculate(s).vanilla,1540);});
test('Single Arcane buys 4% in the explicit budget model',()=>{const s=naked();s.e.items[0]={id:'utility',prefix:'arcane'};const r=B.calculate(s);near(r.maxMana,220);near(r.extra,40);});
test('Damage gain does not compound additively stacked gear',()=>{const s=naked();s.v.armor='hallowed';s.v.items[0]={id:'sorcerer',prefix:'menacing'};near(B.gear(s,'v').damage,38);});
test('Jungle armor aggregation',()=>{const s=naked();s.e.armor='jungle';const g=B.gear(s,'e');near(g.damage,6);near(g.crit,16);near(g.mana,80);});
test('Adamantite armor aggregation',()=>{const s=naked();s.e.armor='adamantite';const g=B.gear(s,'e');near(g.damage,20);near(g.crit,23);near(g.mana,80);});
test('Hallowed armor aggregation',()=>{const s=naked();s.e.armor='hallowed';const g=B.gear(s,'e');near(g.damage,19);near(g.crit,23);near(g.mana,100);});
test('Spectre passive only, no invented proc',()=>{const s=naked();s.e.armor='spectre';near(B.gear(s,'e').damage,25);near(B.gear(s,'e').crit,21);near(s.e.proc,0);});
test('Crit clamps at 100%',()=>{const s=naked();s.e.crit=100;near(B.gear(s,'e').crit,100);near(B.gear(s,'e').multiplier,2/1.04);});
test('Negative crit cannot drop below zero',()=>{const s=naked();s.e.crit=-100;near(B.gear(s,'e').crit,0);});
test('Empty accessories cannot receive prefix bonuses',()=>{const s=naked();s.e.items[0].prefix='arcane';near(B.calculate(s).maxMana,200);});
test('Slots beyond chosen cap are inactive',()=>{const s=naked();s.slots=5;s.e.items[6]={id:'sorcerer',prefix:'arcane'};near(B.calculate(s).elaina,1000);});
test('Manual fixed skill budget has no automatic maximum-mana benefit',()=>{const s=naked();s.budgetSource='manual';near(B.marginal(s).mana,0);});
test('Reserve is subtracted before conversion',()=>{const s=naked();s.extraMana=100;s.reserve=20;s.use=50;near(B.calculate(s).effective,40);});
test('Reserve cannot create a negative output',()=>{const s=naked();s.reserve=10000;near(B.calculate(s).effective,0);});
test('Zero conversion disables bonus output',()=>{const s=B.defaults();s.use=0;near(B.calculate(s).extra,0);});
test('Total pool mode explicitly includes baseline mana',()=>{const s=naked();s.budgetSource='total';near(B.calculate(s).effective,200);near(B.calculate(s).extra,400);});
test('Common stats on skills can be disabled',()=>{const s=naked();s.e.damage=50;s.extraMana=100;s.skillStats=false;near(B.calculate(s).extra,200);s.skillStats=true;near(B.calculate(s).extra,300);});
test('Preset skill list sums cost times quality times realization',()=>{const s=naked();s.mode='skills';near(B.calculate(s).effective,157);near(B.calculate(s).extra,314);});
test('Skill list ignores automatic mana budget parameters',()=>{const s=naked();s.mode='skills';s.use=0;s.quality=0;s.reserve=10000;near(B.calculate(s).effective,157);});
test('Skill realization affects only its own contribution',()=>{const s=naked();s.mode='skills';s.skills.forEach(x=>x.enabled=false);s.skills[0].enabled=true;s.skills[0].realization=50;near(B.calculate(s).effective,50);});
test('No mana marginal gain is invented for unchanged skill list',()=>{const s=naked();s.mode='skills';near(B.marginal(s).mana,0);});
test('No cooldown or mana-reduction axis is present',()=>{const s=B.defaults();assert.equal(s.cooldown,undefined);assert.equal(s.manaReduction,undefined);});
test('Required equivalent budget solves equal DPS',()=>{const s=naked();s.v.damage=40;const r=B.calculate(s);near(r.required,200);s.budgetSource='manual';s.manualBudget=r.required;near(B.calculate(s).elaina,r.vanilla);});
test('Zero rate and positive gap reports impossible instead of NaN',()=>{const s=naked();s.v.damage=40;s.rate=0;assert.equal(B.calculate(s).required,Infinity);});
test('Zero rate and no gap requires no budget',()=>{const s=naked();s.rate=0;near(B.calculate(s).required,0);});
test('Custom proc damage enters output once',()=>{const s=naked();s.v.proc=300;s.e.proc=200;near(B.calculate(s).vanilla,1300);near(B.calculate(s).elaina,1200);near(B.calculate(s).required,50);});
test('Displayed recovery uses local mod parameters, not DPS bonus',()=>{const s=naked();near(B.calculate(s).recovery,9);near(B.calculate(s).elaina,1000);});
test('Changing B scales outputs without changing required budget',()=>{const a=B.defaults(),b=B.clone(a);b.baseDps=a.baseDps*3;const x=B.calculate(a),y=B.calculate(b);near(y.elaina,x.elaina*3);near(y.required,x.required);});
test('Growth experiment uses zero through slot-count prefixes',()=>{const s=B.defaults();const rows=B.growth(s);assert.equal(rows.length,s.slots+1);near(rows[0].e.defense,24);near(rows[6].e.defense,0);near(rows[6].e.mana-rows[0].e.mana,120);});
test('Growth does not mutate configuration',()=>{const s=B.defaults(),before=JSON.stringify(s);B.growth(s);assert.equal(JSON.stringify(s),before);});
test('Marginals do not mutate configuration',()=>{const s=B.defaults(),before=JSON.stringify(s);B.marginal(s);assert.equal(JSON.stringify(s),before);});
test('All default presets produce finite results',()=>{for(const key of Object.keys(B.presets)){const r=B.calculate(B.defaults(key));assert.ok(Number.isFinite(r.vanilla)&&Number.isFinite(r.elaina)&&Number.isFinite(r.required));}});
test('Static IDs are unique',()=>{const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(x=>x[1]);assert.equal(ids.length,new Set(ids).size);});
test('Standalone has no remote script or stylesheet dependency; fixed saving uses a relative loopback endpoint',()=>{assert.ok(!/<script[^>]+src=|<link[^>]+href=/.test(html));assert.ok(html.includes("fetch('/api/skill-balance'"));});
test('Injury defaults to zero and preserves original results',()=>{const s=B.defaults(),r=B.calculate(s);near(s.hurtMana,0);near(r.lostDps,0);near(r.unhurtDps,r.elaina);});
test('Injury subtracts spent mana, not effective mana',()=>{const s=naked();s.extraMana=100;s.quality=.5;s.hurtMana=20;const r=B.calculate(s);near(r.rawBudget,80);near(r.effective,40);near(r.lostDps,20);});
test('Injury never reduces mana maximum, regeneration or auto DPS',()=>{const s=B.defaults(),a=B.calculate(s);s.hurtMana=100;const b=B.calculate(s);near(a.maxMana,b.maxMana);near(a.recovery,b.recovery);near(a.auto,b.auto);near(a.vanilla,b.vanilla);});
test('Injury over budget zeroes skills but cannot subtract ordinary attacks',()=>{const s=B.defaults();s.hurtMana=10000;const r=B.calculate(s);near(r.effective,0);near(r.elaina,r.auto+s.e.proc);near(r.rawBudget,0);});
test('Reserve and conversion happen before net injury deduction',()=>{const s=naked();s.extraMana=200;s.reserve=20;s.use=50;s.hurtMana=30;const r=B.calculate(s);near(r.plannedBudget,90);near(r.rawBudget,60);});
test('Manual budgets also account for injury',()=>{const s=naked();s.budgetSource='manual';s.manualBudget=100;s.hurtMana=20;near(B.calculate(s).effective,80);});
test('Skill list distributes injury proportionally',()=>{const s=naked();s.mode='skills';s.hurtMana=80;const r=B.calculate(s);near(r.plannedBudget,160);near(r.retained,.5);near(r.effective,78.5);near(r.lostDps,157);});
test('Partially realized skills weight both mana and damage',()=>{const s=naked();s.mode='skills';s.skills.forEach(x=>x.enabled=false);s.skills[0].enabled=true;s.skills[0].realization=50;s.hurtMana=20;const r=B.calculate(s);near(r.plannedBudget,50);near(r.effective,30);});
test('No skills or budget produces finite zero injury loss',()=>{const s=naked();s.mode='skills';s.skills.forEach(x=>x.enabled=false);s.hurtMana=200;const r=B.calculate(s);near(r.retained,0);near(r.effective,0);near(r.lostDps,0);});
test('Missing injury property remains compatible in the engine',()=>{const s=B.defaults();delete s.hurtMana;near(B.calculate(s).lostDps,0);});

function setCombat(s,values){
 const {autoCost,autoInterval,...combat}=values;Object.assign(s.combat,combat);
 if(autoCost!==undefined)s.basicAttacks[0].cost=autoCost;
 if(autoInterval!==undefined)s.basicAttacks[0].interval=autoInterval;
}
function combatBase(){const s=naked();s.skills.forEach(x=>x.enabled=false);setCombat(s,{duration:10,potions:0,regenMode:'manual',regen:0,autoCost:0,autoInterval:.5});return s;}
function onlySkill(s){const x=s.skills[0];Object.assign(x,{enabled:true,cost:100,k:1,cd:10,cast:1,delay:0,duration:0,maxCharges:1,initialCharges:1,first:0,priority:1,hit:100});return x;}
function ledger(r){near(r.initialMana+r.regenEffective+r.potionEffective-r.autoMana-r.skillMana-r.hurtPaid,r.endMana);assert.ok(r.endMana>=-1e-7&&r.endMana<=r.maxMana+1e-7);}
test('Combat naked free auto reproduces base DPS',()=>{const r=C.run(combatBase());near(r.dps,1000);near(r.autoCount,20);ledger(r);});
test('Combat fixed mana limits attack count',()=>{const s=combatBase();s.basicAttacks[0].cost=50;const r=C.run(s);near(r.autoCount,4);near(r.endMana,0);near(r.firstShortage,2);ledger(r);});
test('Combat zero opening mana means no free paid attacks',()=>{const s=combatBase();s.combat.startPercent=0;s.basicAttacks[0].cost=3;near(C.run(s).autoDamage,0);});
test('Combat five potions add exactly 2.5 pools when fully spent',()=>{const s=combatBase();setCombat(s,{duration:20,potions:5,autoCost:50});const r=C.run(s);near(r.usedPotions,5);near(r.autoCount,14);near(r.potionEffective,500);near(r.fifthPotionTime,6);near(r.lastPotionTime,6);ledger(r);});
test('Atomic payment does not waste insufficient potion charges',()=>{const s=combatBase();setCombat(s,{startPercent:0,potions:1,autoCost:200});const r=C.run(s);near(r.usedPotions,0);near(r.potionsLeft,1);near(r.autoCount,0);});
test('Atomic payment can use several bottles at once',()=>{const s=combatBase();setCombat(s,{duration:1,startPercent:0,potions:5,autoCost:200});const r=C.run(s);near(r.autoCount,2);near(r.usedPotions,4);ledger(r);});
test('Cost above maximum is never cast in resource simulation',()=>{const s=combatBase();onlySkill(s).cost=201;const r=C.run(s);near(r.skills[0].count,0);assert.equal(r.invalid.length,1);});
test('Unrestricted reference still shows impossible skill potential',()=>{const s=combatBase();onlySkill(s).cost=201;near(C.run(s,true).skills[0].count,1);});
test('WaterBall proposal: cost100 cd10 K0.8 means 1440 extra plus 720 occupancy at B900',()=>{const s=combatBase();s.baseDps=900;s.basicAttacks[0].ratio=.8;const skill=onlySkill(s);skill.k=.8;near(B.skillDamageBudget(s,skill),2160);near(C.run(s).skillDamage,2160);});
test('Cast occupancy is compensated once, not added over uninterrupted autos',()=>{const s=combatBase();onlySkill(s);const r=C.run(s);near(r.autoDamage,9000);near(r.skillDamage,3000);near(r.dps,1200);});
test('Cooldown bounds cast count and excludes an action at the end',()=>{const s=combatBase();s.combat.duration=30;onlySkill(s);near(C.run(s,true).skills[0].count,3);});
test('Initial empty charges recover after a full cooldown',()=>{const s=combatBase();s.combat.duration=20;onlySkill(s).initialCharges=0;const r=C.run(s,true);near(r.skills[0].count,1);near(r.events.find(e=>e.type==='cast').time,10);});
test('Five stored charges refill serially, not five per cooldown',()=>{const s=combatBase();s.combat.duration=25;Object.assign(onlySkill(s),{cast:.1,maxCharges:5,initialCharges:5});near(C.run(s,true).skills[0].count,7);});
test('First release time is respected',()=>{const s=combatBase();s.combat.duration=30;onlySkill(s).first=15;const r=C.run(s,true);near(r.skills[0].count,2);near(r.events.find(e=>e.type==='cast').time,15);});
test('Damage after battle end is not credited',()=>{const s=combatBase();Object.assign(onlySkill(s),{cast:1,delay:20});const r=C.run(s);near(r.skills[0].count,1);near(r.skillDamage,0);});
test('DoT is clipped at battle end',()=>{const s=combatBase();Object.assign(onlySkill(s),{cast:1,delay:0,duration:20});near(C.run(s).skillDamage,3000*9/20);});
test('Hit rate affects damage but not cost',()=>{const s=combatBase();onlySkill(s).hit=50;const r=C.run(s);near(r.skillDamage,1500);near(r.skillMana,100);});
test('Legacy realization and injury do not double-discount combat',()=>{const s=combatBase();onlySkill(s);const a=C.run(s);s.skills[0].realization=0;s.hurtMana=10000;s.use=0;near(C.run(s).dps,a.dps);});
test('Uniform injuries integrate their full requested total',()=>{const s=combatBase();s.combat.hurtTotal=100;const r=C.run(s);near(r.hurtRequested,100);near(r.hurtPaid,100);near(r.endMana,100);ledger(r);});
test('Insufficient defensive mana never goes negative',()=>{const s=combatBase();s.combat.hurtTotal=500;const r=C.run(s);near(r.hurtPaid,200);near(r.uncoveredHurt,300);near(r.endMana,0);});
test('Periodic injuries occur at intervals, not at time zero or T',()=>{const s=combatBase();setCombat(s,{duration:30,hurtMode:'periodic',hurtInterval:10,hurtPerHit:40});near(C.run(s).hurtRequested,80);});
test('Explicit injury event at zero precedes casting',()=>{const s=combatBase();setCombat(s,{hurtMode:'events',hurtEvents:'0:200',autoCost:3});const r=C.run(s);near(r.hurtPaid,200);near(r.autoCount,0);});
test('Injury in the final subframe is not lost',()=>{const s=combatBase();s.combat.hurtMode='events';s.combat.hurtEvents='9.999:40';near(C.run(s).hurtRequested,40);});
test('Malformed and out-of-battle injury lines are reported',()=>{const s=combatBase();s.combat.hurtMode='events';s.combat.hurtEvents='bad\n12:40\n5:20';const r=C.run(s);assert.equal(r.injuryErrors.length,2);near(r.hurtRequested,20);});
test('Full mana regeneration is counted as waste',()=>{const s=combatBase();s.combat.regen=10;const r=C.run(s);near(r.regenWaste,100);near(r.regenEffective,0);ledger(r);});
test('Active reserve prevents skill spending but permits ordinary attack',()=>{const s=combatBase();onlySkill(s);s.combat.reserve=150;const r=C.run(s);near(r.skillMana,0);near(r.dps,1000);});
test('Save strategy can stop autos to accumulate for a ready skill',()=>{const s=combatBase();onlySkill(s);setCombat(s,{startPercent:0,regen:10,autoCost:3,duration:20,policy:'save'});const save=C.run(s);s.combat.policy='flow';const flow=C.run(s);assert.ok(save.skills[0].count>flow.skills[0].count);ledger(save);ledger(flow);});
test('Skill priority chooses the first action deterministically',()=>{const s=combatBase();onlySkill(s);s.skills[2].enabled=true;s.skills[2].priority=1;s.skills[0].priority=2;assert.match(C.run(s,true).events.find(e=>e.type==='cast').text,/炎爆/);});
test('Adding an unpayable skill does not invent extra damage',()=>{const s=combatBase();s.combat.startPercent=0;s.basicAttacks[0].cost=0;const a=C.run(s);onlySkill(s);near(C.run(s).dps,a.dps);});
test('Regen and potion settings do not alter unlimited reference output',()=>{const s=B.defaults();const a=C.run(s,true);s.combat.potions=0;s.combat.regenMode='manual';s.combat.regen=0;near(C.run(s,true).dps,a.dps);});
test('Total damage equals its contributors',()=>{const s=B.defaults();s.e.proc=123;const r=C.run(s);near(r.totalDamage,r.autoDamage+r.skillDamage+r.procDamage);near(r.dps*r.T,r.totalDamage);ledger(r);});
test('Simulation does not mutate input',()=>{const s=B.defaults(),before=JSON.stringify(s);C.compare(s);assert.equal(JSON.stringify(s),before);});
test('Deterministic resource conservation across varied configurations',()=>{for(let n=0;n<16;n++){const s=B.defaults();s.combat.duration=30+n*3;s.combat.potions=n%6;s.combat.hurtTotal=n*35;s.extraMana=n*20;s.combat.startPercent=20+n*5;s.combat.policy=n%2?'flow':'save';s.skills[n%7].enabled=true;const r=C.run(s);ledger(r);assert.ok(r.usedPotions<=s.combat.potions);assert.ok(r.samples.every(x=>x.mana>=-1e-7&&x.mana<=r.maxMana+1e-7));}});

test('Nebula unbuffed armor has 26 damage,16 crit,60 mana and 46 defense',()=>{const s=naked();s.e.armor='nebula';s.e.nebula={damage:0,mana:0,life:0};const g=B.gear(s,'e');near(g.damage,26);near(g.crit,20);near(g.mana,60);near(g.armorDefense,46);near(g.manaReduction,15);near(g.moveSpeed,10);});
test('Full Nebula buffs add 45 damage,30 mana/s and 9 life/s',()=>{const s=naked();s.e.armor='nebula';const g=B.gear(s,'e');near(g.damage,71);near(g.nebulaDamage,45);near(g.nebulaManaRegen,30);near(g.nebulaLifeRegen,9);near(g.crit,20);});
test('Nebula damage is additive to equipment, not a separate 45% multiplier',()=>{const s=naked();s.v.armor='nebula';s.v.damage=20;const g=B.gear(s,'v');near(g.damage,91);near(g.multiplier,1.91*1.2/1.04);});
test('Independent Nebula stack counts apply per buff and per player',()=>{const s=naked();s.v.armor='nebula';s.e.armor='nebula';s.e.nebula={damage:1,mana:2,life:0};const e=B.gear(s,'e'),v=B.gear(s,'v');near(e.damage,41);near(e.nebulaManaRegen,20);near(e.nebulaLifeRegen,0);near(v.damage,71);});
test('Removing Nebula armor disables its stored buffs and mana bridge',()=>{const s=B.defaults('nebula');s.nebulaManaBridge=true;s.e.armor='none';const r=C.run(s);near(B.gear(s,'e').nebulaDamage,0);near(r.nebulaRegen,0);near(r.regen,5+r.maxMana*.02);});
test('Current-code preset does not silently restore special mana',()=>{const s=B.defaults('nebula');assert.equal(s.nebulaManaBridge,false);const r=C.run(s);near(r.nebulaRegen,0);near(r.regen,5+r.maxMana*.02);});
test('Optional Nebula bridge adds exactly 30/s to special regeneration',()=>{const s=B.defaults('nebula'),a=C.run(s);s.nebulaManaBridge=true;const r=C.run(s);near(r.regen,a.regen+30);near(r.nebulaRegen,30);near(B.calculate(s).recovery,r.regen);near(r.maxMana,a.maxMana);ledger(r);});
test('Manual base regen plus Nebula is added exactly once',()=>{const s=B.defaults('nebula');s.nebulaManaBridge=true;s.combat.regenMode='manual';s.combat.regen=7;const r=C.run(s);near(r.baseRegen,7);near(r.regen,37);});
test('Nebula life buff does not create damage, mana or absorb injuries',()=>{const s=B.defaults('nebula');s.combat.hurtTotal=200;const a=C.run(s);s.e.nebula.life=0;const r=C.run(s);near(r.totalDamage,a.totalDamage);near(r.hurtPaid,a.hurtPaid);near(r.endMana,a.endMana);});
test('Nebula 15% vanilla reduction never discounts special skill or auto cost',()=>{const s=combatBase();s.e.armor='nebula';onlySkill(s);s.basicAttacks[0].cost=2;const r=C.run(s);near(r.skillMana,r.skills[0].count*100);near(r.autoMana,r.autoCount*2);});
test('Graduate preset uses KL 3500 base and full buffs on both sides',()=>{const s=B.defaults('nebula');near(s.baseDps,3500);assert.equal(s.v.armor,'nebula');assert.equal(s.e.armor,'nebula');near(B.gear(s,'v').nebulaDamage,45);near(B.gear(s,'e').nebulaLifeRegen,9);});
test('Zero mana stacks cannot grant bridge recovery',()=>{const s=B.defaults('nebula');s.nebulaManaBridge=true;s.e.nebula.mana=0;near(C.run(s).nebulaRegen,0);});
console.log('Default result:', JSON.stringify(B.calculate(B.defaults()),null,2));

function iceDesign() {const s=B.defaults();s.baseDps=1000;const ice={...B.newBasic('IceConeBasic','冰锥'),ratio:.8,cost:10,interval:.5,shots:3};s.basicAttacks.push(ice);s.selectedBasicAttackId=ice.id;return s;}
test('Ice basic: 0.5 seconds / 3 shots / 10 mana distributes one DPS budget',()=>{const s=iceDesign(),r=B.basicBudget(s);near(r.dps,800);near(r.total,400);near(r.perShot,400/3);near(r.manaPerSecond,20);});
test('More shots never multiply the basic attack total damage',()=>{const s=iceDesign();s.basicAttacks[1].shots=6;near(B.basicBudget(s).total,400);near(B.basicBudget(s).perShot,400/6);});
test('Basic mana cost is independent of DPS pricing',()=>{const s=iceDesign();s.basicAttacks[1].cost=30;near(B.basicBudget(s).dps,800);near(B.basicBudget(s).manaPerSecond,60);});
test('Independent basic DPS and interval edits',()=>{const s=iceDesign();Object.assign(s.basicAttacks[1],{ratio:.6,interval:1});near(B.basicBudget(s).dps,600);near(B.basicBudget(s).total,600);near(s.basicAttacks[0].ratio,.8);near(s.basicAttacks[0].cost,3);near(s.basicAttacks[0].interval,.3);});
test('Selected basic drives simulation once and preserves MagicMissile config',()=>{const s=iceDesign();s.skills=[];setCombat(s,{duration:10,regenMode:'manual',regen:0,startPercent:100,potions:0});s.baseMana=1000;const r=C.run(s);near(r.autoCount,20);near(r.autoMana,200);near(r.autoDamage,800*B.gear(s,'e').multiplier*10);near(s.basicAttacks[0].cost,3);});
test('Basic IDs are unique across all skill categories',()=>{const s=iceDesign();assert.ok(B.validBasics(s));s.skills[0].id='IceConeBasic';assert.equal(B.validBasics(s),false);});
test('Invalid basic counts, bounds and selection are rejected',()=>{for(const value of [0,1.5,101,NaN]){const s=iceDesign();s.basicAttacks[1].shots=value;assert.equal(B.validBasics(s),false);}const s=iceDesign();s.selectedBasicAttackId='missing';assert.equal(B.validBasics(s),false);});
test('Generic basic entries are the sole runtime source',()=>{const s=B.defaults();s.basicAttacks[0].ratio=.6;s.basicAttacks[0].cost=7;s.basicAttacks[0].interval=.4;near(B.basicBudget(s).dps,s.baseDps*.6);near(B.selectedBasic(s).cost,7);near(B.selectedBasic(s).interval,.4);});
test('Missile progression has two upgrades per stage excluding learned level',()=>{const r=B.newBasic();assert.deepEqual(Array.from(B.progressionNodes(r,5,15)),[1,3,5,8,10,13,15]);near(B.skillLevelAt(r,5),3);near(B.skillLevelAt(r,10),5);});
test('Ice phase cap and first level are distinct',()=>{const r={...B.newBasic(),unlockStageCap:10,unlockLevel:6};assert.deepEqual(Array.from(B.progressionNodes(r,5,15)),[6,8,10,13,15]);near(B.skillLevelAt(r,5),0);near(B.skillLevelAt(r,8),2);r.unlockLevel=10;assert.deepEqual(Array.from(B.progressionNodes(r,5,15)),[10,13,15]);});
test('Progression does not duplicate integer gates or truncate at 64 skills',()=>{const r={...B.newBasic(),levelsPerPhase:10};const nodes=B.progressionNodes(r,1,1000);assert.equal(new Set(nodes).size,nodes.length);near(B.skillLevelAt(r,1000,1),1000);});
test('Level curve and rounded damage expose weak early upgrades',()=>{const s=B.defaults(),r=s.basicAttacks[0];near(B.levelDps(1),22);near(B.levelDps(3),26);near(B.levelDps(5),30);near(B.levelDps(10),50);near(B.levelDps(1000),3500);assert.deepEqual([1,3,5].map(l=>B.progressionBudget(s,r,l).integerHit),[5,6,7]);});
test('Progression preview does not alter current pricing or runtime simulation',()=>{const s=B.defaults(),before=B.basicBudget(s).dps;B.progressionBudget(s,s.basicAttacks[0],1);near(B.basicBudget(s).dps,before);});
console.log(`\n${count} model/static tests passed.`);
async function browserTests(){
 // Isolated disposable browser for this local HTML; no user browser profile or session is used.
 const runtime = process.env.CODEX_NODE_MODULES || path.join(require('node:os').homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules');
 const {chromium}=require(path.join(runtime,'playwright'));
 const browser=await chromium.launch({headless:true, channel:process.env.BALANCE_BROWSER_CHANNEL || 'chrome'});
 try {
  fs.mkdirSync(path.join(__dirname,'test-output'),{recursive:true});
  const page=await browser.newPage({viewport:{width:1440,height:1100},deviceScaleFactor:1});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  const resetPage=async(accept=true)=>{
   await page.locator('#moreActions summary').click();
   page.once('dialog',dialog=>accept?dialog.accept():dialog.dismiss());
   await page.locator('#reset').click();
   assert.equal(await page.locator('#moreActions').evaluate(el=>el.open),false);
  };
  await page.goto(pathToFileURL(htmlPath).href);
  assert.equal(await page.locator('#import,#importFile,#export').count(),0,'Obsolete import/export UI is removed');
  assert.equal(await page.locator('header button:visible').count(),2,'Only save and reload are primary buttons');
  assert.equal(await page.locator('#reset').isVisible(),false);
  await page.locator('#moreActions summary').focus();
  await page.keyboard.press('Enter');
  assert.equal(await page.locator('#reset').isVisible(),true);
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#reset').isVisible(),false);
  assert.equal(await page.locator('#moreActions summary').evaluate(el=>el===document.activeElement),true);
  await page.locator('#moreActions summary').click();
  await page.locator('h1').click();
  assert.equal(await page.locator('#reset').isVisible(),false);
  await page.locator('#baseDps').fill('1234');
  await resetPage(false);
  assert.equal(await page.locator('#baseDps').inputValue(),'1234','Cancel reset preserves edits');
  await page.screenshot({path:path.join(__dirname,'test-output','toolbar-desktop.png'),clip:{x:0,y:0,width:1440,height:260}});
  await page.setViewportSize({width:390,height:844});
  await page.locator('#moreActions summary').click();
  await page.screenshot({path:path.join(__dirname,'test-output','toolbar-mobile.png')});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.keyboard.press('Escape');
  await page.setViewportSize({width:1440,height:1100});
  await resetPage();

  const progressionPanel=page.locator('#progressionPanel');
  const progressionToggle=progressionPanel.locator('summary');
  assert.equal(await progressionPanel.evaluate(el=>el.open),false,'Progression preview starts collapsed');
  assert.equal(await page.locator('#progressionPhaseSize').isVisible(),false);
  const collapsedHeight=(await progressionPanel.boundingBox()).height;
  await progressionPanel.screenshot({path:path.join(__dirname,'test-output','progression-collapsed.png')});
  await progressionToggle.click();
  assert.equal(await progressionPanel.evaluate(el=>el.open),true);
  assert.ok((await progressionPanel.boundingBox()).height>collapsedHeight+200,'Collapsing must reclaim preview space');

  // Configurable skill progression: two upgrades per five-level phase for small attacks.
  await page.getByRole('button',{name:'添加冰锥示例',exact:true}).click();
  assert.equal(await page.locator('#progressionRows tr').count(),B.defaults().skills.length+2);
  assert.equal(await page.getByRole('spinbutton',{name:'冰锥普攻首级角色等级',exact:true}).inputValue(),'6');
  assert.equal(await page.getByRole('spinbutton',{name:'冰锥普攻每阶段新增技能等级',exact:true}).inputValue(),'2');
  const progressionText=await page.locator('#progressionRows tr').filter({hasText:'冰锥普攻'}).innerText();
  assert.match(progressionText,/Lv1→6、Lv2→8、Lv3→10/);
  assert.match(progressionText,/Lv3（角色 10）/);
  await page.getByRole('spinbutton',{name:'魔法飞弹首级角色等级',exact:true}).fill('1');
  await page.getByRole('spinbutton',{name:'魔法飞弹每阶段新增技能等级',exact:true}).fill('2');
  const missileProgression=await page.locator('#progressionRows tr').filter({hasText:'魔法飞弹'}).innerText();
  assert.match(missileProgression,/Lv1→1、Lv2→3、Lv3→5/);
  assert.match(missileProgression,/Lv5（角色 10）/);
  await page.locator('#progressionPanel').screenshot({path:path.join(__dirname,'test-output','progression-design.png')});
  assert.equal(await progressionPanel.evaluate(el=>el.open),true,'Editing must not close the preview');
  await progressionToggle.focus();
  await page.keyboard.press('Enter');
  assert.equal(await page.locator('#progressionPhaseSize').isVisible(),false);
  await page.setViewportSize({width:390,height:844});
  await progressionPanel.screenshot({path:path.join(__dirname,'test-output','progression-collapsed-mobile.png')});
  await progressionToggle.click();
  assert.equal(await page.locator('#progressionPhaseSize').isVisible(),true);
  assert.equal(await page.getByRole('spinbutton',{name:'魔法飞弹每阶段新增技能等级',exact:true}).inputValue(),'2');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false);
  await progressionPanel.screenshot({path:path.join(__dirname,'test-output','progression-expanded-mobile.png')});
  await progressionToggle.click();
  await page.setViewportSize({width:1440,height:1100});
  await page.reload();
  assert.equal(await progressionPanel.evaluate(el=>el.open),false,'Reload returns to compact default');
  await resetPage();

  // Independent ordinary-attack design, persistence, deletion and backward migration.
  await page.locator('#baseDps').fill('1000');
  await page.getByRole('button',{name:'添加冰锥示例',exact:true}).click();
  assert.equal(await page.locator('#basicRows tr').count(),2);
  assert.equal(await page.locator('#basicDps1').innerText(),'800');
  assert.equal(await page.locator('#basicTotal1').innerText(),'400');
  assert.equal(await page.locator('#basicHit1').innerText(),'133.33');
  assert.equal(await page.locator('#basicMana1').innerText(),'20');
  await page.getByRole('spinbutton',{name:'冰锥普攻目标DPS倍率',exact:true}).fill('0.6');
  assert.equal(await page.locator('#basicDps1').innerText(),'600');
  assert.equal(await page.locator('#basicHit1').innerText(),'100');
  const basicSaved=await page.evaluate(()=>JSON.parse(localStorage.getItem('elaina-mage-balance-v2')));
  near(basicSaved.basicAttacks[0].ratio,.8);near(basicSaved.basicAttacks[0].cost,3);near(basicSaved.basicAttacks[0].interval,.3);
  await page.locator('#basicTable').evaluate(el=>el.closest('section').scrollIntoView());
  await page.locator('[aria-label="普通攻击设计"]').screenshot({path:path.join(__dirname,'test-output','basic-design.png')});
  await resetPage();
  await page.evaluate(value=>localStorage.setItem('elaina-mage-balance-v2',JSON.stringify(value)),basicSaved);
  await page.reload();
  assert.equal(await page.locator('#basicHit1').innerText(),'100');
  await page.locator('#preset').selectOption('jungle');
  assert.equal(await page.locator('#basicRows tr').count(),2,'Changing stage must preserve ordinary attack drafts');
  await page.locator('#baseDps').fill('1000');

  await page.reload();
  assert.equal(await page.locator('#basicHit1').innerText(),'100');
  assert.equal(await page.getByRole('radio',{name:'使用冰锥普攻作为参考普攻'}).isChecked(),true);
  await page.getByRole('button',{name:'添加普通攻击',exact:true}).click();
  assert.equal(await page.locator('#basicRows tr').count(),3);
  await page.getByRole('button',{name:'删除普攻新普攻 1',exact:true}).click();
  assert.equal(await page.getByRole('radio',{name:'使用魔法飞弹作为参考普攻'}).isChecked(),true);
  await page.getByRole('button',{name:'删除普攻冰锥普攻',exact:true}).click();
  await resetPage();

  await page.evaluate(()=>{
   window.testFile={name:'SkillBalance.json',text:'',picks:0,writes:0};
   window.showOpenFilePicker=async()=>{window.testFile.picks++;return [{name:window.testFile.name,
    queryPermission:async()=>window.testFile.denied?'denied':'granted',requestPermission:async()=>window.testFile.denied?'denied':'granted',
    getFile:async()=>({text:async()=>window.testFile.text}),
    createWritable:async()=>({write:async text=>{if(window.testFile.fail)throw new Error('test write failure');window.testFile.pending=text;},close:async()=>{window.testFile.text=window.testFile.pending;window.testFile.writes++;},abort:async()=>{}})
   }];};
  });
  await page.getByRole('button',{name:'保存到模组',exact:true}).click();
  await page.waitForFunction(()=>!document.getElementById('saveMod').disabled);
  assert.match(await page.locator('#fileStatus').innerText(),/已保存/);
  const savedDirect=await page.evaluate(()=>JSON.parse(window.testFile.text));
  assert.equal(savedDirect.schema,'elaina-mage-balance-v2');
  assert.equal(savedDirect.configuration.autoRatio,undefined);
  assert.deepEqual(Object.keys(savedDirect).sort(),['configuration','schema'],'Save contains parameters, not calculated logs');
  await page.getByRole('button',{name:'保存到模组',exact:true}).click();
  await page.waitForFunction(()=>!document.getElementById('saveMod').disabled);
  assert.equal(await page.evaluate(()=>window.testFile.picks),1,'Subsequent saves reuse the selected handle');
  assert.equal(await page.evaluate(()=>window.testFile.writes),2);
  await page.keyboard.press('Control+s');
  await page.waitForFunction(()=>window.testFile.writes===3);
  const beforeResetFile=await page.evaluate(()=>window.testFile.text);
  await resetPage();
  assert.equal(await page.evaluate(()=>window.testFile.text),beforeResetFile,'Reset does not overwrite the mod file');
  assert.match(await page.locator('#status').innerText(),/尚未写入模组文件/);
  await page.locator('#baseDps').fill('1234');
  await page.getByRole('button',{name:'重新读取',exact:true}).click();
  await page.waitForFunction(()=>document.getElementById('baseDps').value!=='1234');
  assert.equal(await page.locator('#baseDps').inputValue(),String(savedDirect.configuration.baseDps));
  await page.evaluate(()=>{window.testFile.denied=true;});
  await page.getByRole('button',{name:'保存到模组',exact:true}).click();
  await page.waitForFunction(()=>!document.getElementById('saveMod').disabled);
  assert.match(await page.locator('#fileStatus').innerText(),/未获得/);
  assert.equal(await page.evaluate(()=>window.testFile.writes),3,'Denied permission must not write');
  await page.evaluate(()=>{window.testFile.denied=false;window.testFile.fail=true;});
  await page.getByRole('button',{name:'保存到模组',exact:true}).click();
  await page.waitForFunction(()=>!document.getElementById('saveMod').disabled);
  assert.match(await page.locator('#fileStatus').innerText(),/test write failure/);
  assert.equal(await page.evaluate(()=>window.testFile.writes),3,'Failed write must not close or report success');
  await page.evaluate(()=>{window.testFile.fail=false;});

  await page.evaluate(()=>{window.testFile.denied=false;window.testFile.name='wrong.json';});
  await page.getByRole('button',{name:'更换…',exact:true}).click();
  await page.waitForFunction(()=>document.getElementById('fileStatus').textContent.includes('请选择模组'));
  assert.match(await page.locator('#fileStatus').innerText(),/请选择模组/);
  await page.evaluate(()=>{window.showOpenFilePicker=async()=>{throw new DOMException('cancel','AbortError');};});
  await page.getByRole('button',{name:'更换…',exact:true}).click();
  assert.match(await page.locator('#fileStatus').innerText(),/已取消/);

  // Bulk prefixes change only the requested side's active, occupied slots.
  const values=async(side,prop)=>page.locator('#'+side+'Slots select[data-prop="'+prop+'"]').evaluateAll(els=>els.map(el=>el.value));
  const initialVItems=await values('v','id'),initialEItems=await values('e','id');
  const initialEPrefixes=await values('e','prefix');
  const beforePrefixDps=await page.locator('#simVanilla').innerText();
  await page.getByRole('button',{name:'原版法师全险恶',exact:true}).click();
  assert.ok((await values('v','prefix')).every(v=>v==='menacing'));
  assert.deepEqual(await values('e','prefix'),initialEPrefixes);
  assert.notEqual(await page.locator('#simVanilla').innerText(),beforePrefixDps);
  await page.getByRole('button',{name:'原版法师全奥秘',exact:true}).click();
  assert.ok((await values('v','prefix')).every(v=>v==='arcane'));
  await page.getByRole('button',{name:'伊蕾娜全险恶',exact:true}).click();
  assert.ok((await values('e','prefix')).every(v=>v==='menacing'));
  const beforeArcane=await page.locator('#simCapacity').innerText();
  await page.getByRole('button',{name:'伊蕾娜全奥秘',exact:true}).click();
  assert.ok((await values('e','prefix')).every(v=>v==='arcane'));
  assert.notEqual(await page.locator('#simCapacity').innerText(),beforeArcane);
  assert.deepEqual(await values('v','id'),initialVItems);
  assert.deepEqual(await values('e','id'),initialEItems);
  await page.reload();
  assert.ok((await values('v','prefix')).every(v=>v==='arcane'));
  assert.ok((await values('e','prefix')).every(v=>v==='arcane'));
  await page.locator('#slots').selectOption('7');
  await page.locator('#eSlots select[data-prop="prefix"]').nth(6).selectOption('lucky');
  await page.locator('#slots').selectOption('5');
  await page.locator('#eSlots select[data-prop="id"]').first().selectOption('empty');
  await page.locator('#eSlots select[data-prop="prefix"]').first().selectOption('warding');
  await page.getByRole('button',{name:'伊蕾娜全险恶',exact:true}).click();
  assert.deepEqual(await values('e','prefix'),['warding','menacing','menacing','menacing','menacing']);
  assert.match(await page.locator('#ePrefixStatus').innerText(),/4 个/);
  await page.locator('#slots').selectOption('7');
  assert.equal((await values('e','prefix'))[6],'lucky');
  await resetPage();

  // Graduate preset, three independent buff stacks and explicit special-mana adaptation.
  await page.locator('#preset').selectOption('nebula');
  assert.equal(await page.locator('#baseDps').inputValue(),'3500');
  assert.ok(await page.locator('#vNebula').isVisible());
  assert.ok(await page.locator('#eNebula').isVisible());
  assert.equal(await page.locator('#vNebulaDamage').inputValue(),'3');
  assert.equal(await page.locator('#eNebulaMana').inputValue(),'3');
  assert.equal(await page.locator('#nebulaManaBridge').isChecked(),false);
  assert.match(await page.locator('#eNebulaInfo').innerText(),/\+45% 加算伤害、\+30 原版魔力\/秒、\+9 生命\/秒/);
  const fullNebulaDps=await page.locator('#simVanilla').innerText();
  await page.locator('#vNebulaDamage').selectOption('0');
  assert.notEqual(await page.locator('#simVanilla').innerText(),fullNebulaDps);
  assert.equal(await page.locator('#eNebulaDamage').inputValue(),'3');
  await page.getByRole('button',{name:'原版法师星云强化全满',exact:true}).click();
  assert.equal(await page.locator('#simVanilla').innerText(),fullNebulaDps);
  const beforeBridge=await page.locator('#simCapacity').innerText();
  await page.locator('#nebulaManaBridge').check();
  assert.notEqual(await page.locator('#simCapacity').innerText(),beforeBridge);
  assert.match(await page.locator('#simCapacity').innerText(),/星云 30/);
  await page.locator('#eNebulaMana').selectOption('1');
  assert.match(await page.locator('#simCapacity').innerText(),/星云 10/);
  await page.reload();
  assert.equal(await page.locator('#nebulaManaBridge').isChecked(),true);
  assert.equal(await page.locator('#eNebulaMana').inputValue(),'1');
  await page.getByRole('button',{name:'伊蕾娜星云强化全满',exact:true}).click();
  await page.locator('#eNebula').screenshot({path:path.join(__dirname,'test-output','nebula-buffs.png')});
  await page.setViewportSize({width:390,height:844});
  await page.locator('#eNebula').screenshot({path:path.join(__dirname,'test-output','nebula-mobile.png')});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false);
  await page.setViewportSize({width:1440,height:1100});
  await page.locator('#eArmor').selectOption('hallowed');
  assert.equal(await page.locator('#eNebula').isVisible(),false);
  assert.doesNotMatch(await page.locator('#simCapacity').innerText(),/星云/);
  await page.locator('#vNebulaLife').selectOption('1');
  await page.getByRole('button',{name:'复制左侧装备 · 前缀转奥秘'}).click();
  assert.equal(await page.locator('#eNebulaLife').inputValue(),'1');
  await resetPage();
  // Exercise the new resource-limited simulation before the legacy-budget regression suite.
  const initialSim=await page.locator('#simActual').innerText();
  const initialIdeal=await page.locator('#simIdeal').innerText();
  await page.locator('#battlePotions').fill('0');
  assert.notEqual(await page.locator('#simActual').innerText(),initialSim);
  assert.equal(await page.locator('#simIdeal').innerText(),initialIdeal);
  assert.equal(await page.locator('#simPotionEnd').innerText(),'未携带');
  await page.getByRole('button',{name:'长战 180 秒',exact:true}).click();
  assert.equal(await page.locator('#battleDuration').inputValue(),'180');
  await page.locator('#battleRegenMode').selectOption('manual');
  await page.locator('#battleRegen').fill('0');
  await page.locator('#battleStart').fill('0');
  assert.equal(await page.locator('#simActual').innerText(),'0');
  await page.locator('#battlePolicy').selectOption('save');
  await resetPage();
  await page.getByText('受伤损蓝：均匀损失、周期受击或指定时间',{exact:true}).click();
  await page.locator('#battleHurtTotal').fill('500');
  assert.notEqual(await page.locator('#simActual').innerText(),initialSim);
  await page.locator('#battleHurtMode').selectOption('events');
  await page.locator('#battleHurtEvents').fill('0:380\nbad\n150:20');
  assert.match(await page.locator('#simWarnings').innerText(),/格式错误/);
  await page.locator('#battleHurtMode').selectOption('periodic');
  assert.ok(await page.locator('#battleHurtInterval').isVisible());
  await page.locator('#battleHurtPerHit').fill('50');
  await page.locator('#battleHurtInterval').fill('20');
  await page.getByRole('checkbox',{name:'模拟启用冰凌锁',exact:true}).check();
  await page.getByRole('spinbutton',{name:'模拟冰凌锁蓝耗',exact:true}).fill('500');
  assert.match(await page.locator('#simWarnings').innerText(),/无法支付/);
  await page.getByRole('spinbutton',{name:'模拟水球魔法CD',exact:true}).fill('30');
  await page.getByRole('spinbutton',{name:'模拟水球魔法命中',exact:true}).fill('50');
  await page.reload();
  assert.equal(await page.getByRole('spinbutton',{name:'模拟水球魔法CD',exact:true}).inputValue(),'30');
  assert.equal(await page.locator('#battleHurtMode').inputValue(),'periodic');
  await resetPage();
  await page.locator('#legacyResults > summary').click();
  await page.locator('#vDps').waitFor();
  const beforeHurt=await page.locator('#eDps').innerText();
  await page.locator('#hurtMana').fill('60');
  assert.notEqual(await page.locator('#eDps').innerText(),beforeHurt);
  assert.equal(await page.locator('#mana').innerText(),'380');
  assert.equal(await page.locator('#effective').innerText(),'120');
  await page.reload();
  await page.locator('#legacyResults').evaluate(el=>el.open=true);
  assert.equal(await page.locator('#hurtMana').inputValue(),'60');
  await page.locator('#hurtMana').fill('10000');
  assert.equal(await page.locator('#effective').innerText(),'0');
  assert.match(await page.locator('#hurtExplain').innerText(),/超出部分不继续扣普攻/);
  await page.locator('#hurtMana').fill('0');
  assert.equal(await page.locator('#eDps').innerText(),beforeHurt);
  const before=await page.locator('#eDps').innerText();
  await page.locator('#extraMana').fill('200');
  assert.notEqual(await page.locator('#eDps').innerText(),before);
  await page.locator('#use').fill('0');
  assert.match(await page.locator('#eDetail').innerText(),/技能 0/);
  await page.locator('#mode').selectOption('skills');
  assert.ok(await page.locator('#skillControls').isVisible());
  assert.ok(!(await page.locator('#budgetControls').isVisible()));
  assert.equal(await page.locator('#effective').innerText(),'157');
  await page.locator('#hurtMana').fill('80');
  assert.equal(await page.locator('#effective').innerText(),'78.5');
  assert.equal(await page.locator('#skillValue0').innerText(),'50');
  await page.locator('#hurtMana').fill('0');
  await page.getByRole('checkbox',{name:'启用水球魔法',exact:true}).uncheck();
  assert.equal(await page.locator('#effective').innerText(),'57');
  await page.locator('#slots').selectOption('7');
  assert.equal(await page.locator('#eSlots .slot').count(),7);
  await page.getByRole('button',{name:'复制左侧装备 · 前缀转奥秘'}).click();
  assert.equal(await page.locator('#eSlots select[data-prop="prefix"]').first().inputValue(),'arcane');
  await page.reload();
  await page.locator('#legacyResults').evaluate(el=>el.open=true);
  assert.equal(await page.locator('#slots').inputValue(),'7');
  assert.equal(await page.locator('#mode').inputValue(),'skills');
  await page.locator('#preset').selectOption('spectre');
  assert.equal(await page.locator('#baseDps').inputValue(),'1800');
  assert.match(await page.locator('#vSummary').innerText(),/追击未自动计入/);
  await page.locator('#vSlots select[data-prop="id"]').nth(1).selectOption('sorcerer');
  assert.match(await page.locator('#vSummary').innerText(),/重复装备/);
  await resetPage();
  const out=path.join(__dirname,'test-output');fs.mkdirSync(out,{recursive:true});
  await page.locator('#hurtMana').fill('60');
  await page.getByText('受伤损蓝：均匀损失、周期受击或指定时间',{exact:true}).evaluate(el=>el.parentElement.open=true);
  await page.locator('#battleHurtMode').selectOption('uniform');
  await page.locator('#battleHurtTotal').fill('240');
  await page.screenshot({path:path.join(out,'desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:path.join(out,'mobile.png'),fullPage:true});
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);
  assert.equal(overflow,false,'Mobile document must not overflow horizontally');
  await page.locator('#mode').selectOption('skills');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false);
  await page.setViewportSize({width:1440,height:1100});
  await resetPage();
  const exported={schema:'elaina-mage-balance-v2',configuration:B.defaults()};
  assert.ok(await page.getByText('魔力转换率 K',{exact:true}).count());
  await page.getByRole('button',{name:'添加主动技能'}).click();
  const added=page.locator('#rotationRows tr').last();
  await added.getByRole('textbox',{name:/技能名称/}).fill('<试炼&飞弹>');
  await added.getByRole('textbox',{name:/技能 ID/}).fill('ExperimentalSkill');
  await added.getByRole('checkbox').check();
  await added.getByRole('spinbutton',{name:'模拟<试炼&飞弹>蓝耗'}).fill('100');
  assert.equal(await page.locator('#rotationRows tr').count(),B.defaults().skills.length+1);
  assert.equal(await page.locator('#rotationRows img').count(),0,'User-provided skill names must be escaped');
  await page.reload();
  assert.equal(await page.locator('#rotationRows tr').count(),B.defaults().skills.length+1);
  assert.equal(await page.locator('#rotationRows tr').last().getByRole('textbox',{name:/技能 ID/}).inputValue(),'ExperimentalSkill');
  const extraExport={schema:'elaina-mage-balance-v2',configuration:await page.evaluate(()=>JSON.parse(localStorage.getItem('elaina-mage-balance-v2')))};
  assert.equal(extraExport.configuration.skills.at(-1).name,'<试炼&飞弹>');
  await resetPage();


  // Exercise the remaining file-reload path using an isolated in-memory handle.
  const loadPayload=async(value)=>{
   const payload=value&&typeof value==='object'&&!Array.isArray(value)&&!Object.hasOwn(value,'schema')?{schema:'elaina-mage-balance-v2',configuration:value}:value;
   await page.evaluate(text=>{
    window.showOpenFilePicker=async()=>[{name:'SkillBalance.json',queryPermission:async()=> 'granted',requestPermission:async()=> 'granted',getFile:async()=>({text:async()=>text})}];
    document.getElementById('fileStatus').textContent='';
   },typeof payload==='string'?payload:JSON.stringify(payload));
   await page.locator('#linkMod').click();
   await page.waitForFunction(()=>document.getElementById('fileStatus').textContent.includes('已关联'));
   await page.locator('#fileStatus').evaluate(el=>el.textContent='');
   await page.locator('#loadMod').click();
   await page.waitForFunction(()=>document.getElementById('fileStatus').textContent!=='');
  };
  await page.locator('#extraMana').fill('900');
  const duplicate=B.clone(extraExport.configuration);duplicate.skills.at(-1).id=duplicate.skills[0].id;
  await loadPayload(duplicate);assert.match(await page.locator('#fileStatus').innerText(),/读取失败/);
  const malicious=B.clone(extraExport.configuration);malicious.skills.at(-1).name='<img src=x onerror=window.injected=1>';
  await loadPayload(malicious);
  assert.equal(await page.locator('#rotationRows img,#rotationResults img,#combatEvents img,#skillRows img').count(),0,'Names must not be interpreted as HTML');
  assert.equal(await page.evaluate(()=>window.injected),undefined);
  const empty=B.clone(extraExport.configuration);empty.skills=[];await loadPayload(empty);
  assert.equal(await page.locator('#rotationRows tr').count(),0,'Zero active skills is a valid auto-only plan');
  await loadPayload(extraExport);
  assert.equal(await page.locator('#rotationRows tr').count(),B.defaults().skills.length+1,'Extra skills must survive file reload');
  await page.locator('#rotationRows tr').last().getByRole('button',{name:/删除/}).click();
  assert.equal(await page.locator('#rotationRows tr').count(),B.defaults().skills.length);
  await loadPayload(exported);
  assert.equal(await page.locator('#extraMana').inputValue(),'0');
  assert.match(await page.locator('#fileStatus').innerText(),/已读取/);
  near(Number((await page.locator('#simActual').innerText()).replaceAll(',','')),Math.round(C.run(exported.configuration).dps*10)/10);
  const customized=B.defaults('nebula');customized.extraMana=240;customized.nebulaManaBridge=true;customized.combat.duration=180;customized.e.nebula.life=1;customized.skills[0].cost=130;
  await loadPayload({schema:'elaina-mage-balance-v2',configuration:customized,result:{elaina:-123},combat:{actual:{dps:-123}}});
  assert.equal(await page.locator('#preset').inputValue(),'nebula');
  assert.equal(await page.locator('#battleDuration').inputValue(),'180');
  assert.equal(await page.locator('#eNebulaLife').inputValue(),'1');
  assert.equal(await page.getByRole('spinbutton',{name:'模拟水球魔法蓝耗',exact:true}).inputValue(),'130');
  assert.equal(await page.locator('#nebulaManaBridge').isChecked(),true);
  await page.reload();
  assert.equal(await page.locator('#extraMana').inputValue(),'240');
  const retained=await page.locator('#simActual').innerText();
  for(const bad of ['{bad json',null,[],{schema:'future',configuration:customized},{version:2}, {...customized,baseDps:1000001},{...customized,preset:'toString'},{...customized,skills:[null]}]){
   await loadPayload(bad===null?'null':bad);
   assert.match(await page.locator('#fileStatus').innerText(),/读取失败，当前配置未改变/);
   assert.equal(await page.locator('#extraMana').inputValue(),'240');
   assert.equal(await page.locator('#simActual').innerText(),retained);
  }
  const invalidArmor=B.clone(customized);invalidArmor.e.armor='constructor';await loadPayload(invalidArmor);
  assert.match(await page.locator('#fileStatus').innerText(),/读取失败/);
  const legacyImport=B.clone(customized);legacyImport.version=1;
  await loadPayload({schema:'elaina-mage-balance-v1',configuration:legacyImport});
  assert.match(await page.locator('#fileStatus').innerText(),/读取失败/);
  // Re-selecting the same file remains possible; unknown payload keys are not stored.
  await loadPayload({...customized,unexpected:'discard me'});
  await loadPayload({...customized,unexpected:'discard me'});
  assert.equal(await page.evaluate(()=>Object.hasOwn(JSON.parse(localStorage.getItem('elaina-mage-balance-v2')),'unexpected')),false);
  await resetPage();
  await page.locator('#extraMana').fill('120');
  await loadPayload(JSON.parse(fs.readFileSync(path.join(__dirname,'elaina-mage-balance.json'),'utf8')));
  assert.match(await page.locator('#fileStatus').innerText(),/已读取/,'Existing saved JSON must remain readable');
  assert.deepEqual(errors,[]);
  console.log('Browser smoke passed: budget/skill updates, presets, slot count, copy, persistence, duplicate warning, compact toolbar, file reload, desktop/mobile layout; zero JS errors.');
 } finally {await browser.close();}
}
if(process.argv.includes('--browser'))browserTests().catch(e=>{console.error(e);process.exitCode=1;});

